### ISSUE TITLE
lando-messaging pickling issue

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin#6]
During the upgrade to python3 we found that messages sent from bespin-api(python3) could not be read by lando(python2) and images containing lando. There is an option to specify the protocol in the `dumps` command: https://docs.python.org/3/library/pickle.html#pickle.dumps
To try and keep the older images compatible we can use this option.

We need to 
- change [lando-messaging](https://github.com/Duke-GCB/lando-messaging) to set the protocol to 2
- update lando-messaging in bespin-api, bespin-mailer, and lando
- update lando to python3

**Comment by dleehr** [comment]
I think this issue, while impacting other repos, clearly has a home in lando-messaging. Let's use this repo for issues that don't otherwise have a home.
